name: Unit Test

on: [ push ]

jobs:
  PHPUnit:
    strategy:
      matrix:
        include:
            # Laravel 6.*
            -   php: 7.4
                laravel: 6.*
                testbench: 4.*
                composer-flag: '--prefer-stable'
            -   php: 8.0
                laravel: 6.*
                testbench: 4.*
                composer-flag: '--prefer-stable'
            # Laravel 7.*
            -   php: 7.4
                laravel: 7.*
                testbench: 5.*
                composer-flag: '--prefer-stable'
            -   php: 8.0
                laravel: 7.*
                testbench: 5.*
                composer-flag: '--prefer-stable'
            # Laravel 8.*
            -   php: 7.4
                laravel: 8.*
                testbench: 6.*
                composer-flag: '--prefer-stable'
            -   php: 8.0
                laravel: 8.*
                testbench: 6.*
                composer-flag: '--prefer-stable'
            -   php: 8.1
                laravel: 8.*
                testbench: 6.*
                composer-flag: '--prefer-stable'
            # Laravel 9.*
            -   php: 8.0
                laravel: 9.*
                testbench: 7.*
                composer-flag: '--prefer-stable'
            -   php: 8.1
                laravel: 9.*
                testbench: 7.*
                composer-flag: '--prefer-stable'
            # Laravel 10.*
            -   php: 8.1
                laravel: 10.*
                testbench: 8.*
                composer-flag: '--prefer-stable'
            -   php: 8.2
                laravel: 10.*
                testbench: 8.*
                composer-flag: '--prefer-stable'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv
            coverage: xdebug

      - name: Install dependencies
        run: composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update

      - name: Update dependencies
        run: composer update ${{ matrix.composer-flag }} --prefer-dist --no-interaction

      - name: Run PHPUnit
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
